version: "3.9"
services:
  web-service:
    image: ea-project:$WEB_SERVICE_TAG
    ports:
      - "8080"
    restart: always
    networks:
      - ea

  load-balancer:
    image: nginx:latest
    volumes:
      - ./deploy/nginx/conf/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
    networks:
      - ea
    depends_on:
      - web-service

networks:
  ea: